import {
  Truck, Trash2, Snowflake, Wrench, Layers, PaintBucket,
  Leaf, Droplets, RefreshCcw, HelpCircle, HardHat, Sparkles, Home,
  type LucideIcon,
} from "lucide-react";

export interface ServiceConfig {
  key: string;
  label: string;
  tags: string[];
  icon: LucideIcon;
  headerGradient: string;
  iconBg: string;
  iconColor: string;
  glowColor: string;
  ringColor: string;
  crew: [number, number];
  duration: [number, number];
  earn: [number, number];
  description: string;
  status?: "active" | "coming-soon";
}

export const SERVICES: ServiceConfig[] = [
  {
    key: "residential",
    label: "Moving",
    tags: ["Residential", "Local & Long Distance"],
    icon: Truck,
    headerGradient: "from-blue-500 to-blue-700",
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-400",
    glowColor: "shadow-blue-500/40",
    ringColor: "ring-blue-500",
    crew: [2, 4],
    duration: [2, 8],
    earn: [300, 750],
    description: "Full-service local & long-distance movers",
  },
  {
    key: "junk",
    label: "Junk Removal",
    tags: ["Haul Away", "Disposal"],
    icon: Trash2,
    headerGradient: "from-orange-500 to-orange-700",
    iconBg: "bg-orange-500/10",
    iconColor: "text-orange-400",
    glowColor: "shadow-orange-500/40",
    ringColor: "ring-orange-500",
    crew: [1, 3],
    duration: [1, 4],
    earn: [150, 500],
    description: "Fast, clean haul-away — no mess left behind",
  },
  {
    key: "snow",
    label: "Snow Removal",
    tags: ["Plowing", "Shoveling"],
    icon: Snowflake,
    headerGradient: "from-cyan-500 to-cyan-700",
    iconBg: "bg-cyan-500/10",
    iconColor: "text-cyan-400",
    glowColor: "shadow-cyan-500/40",
    ringColor: "ring-cyan-500",
    crew: [1, 2],
    duration: [1, 3],
    earn: [75, 200],
    description: "Driveways, walkways & parking lots cleared fast",
  },
  {
    key: "handyman",
    label: "Handyman",
    tags: ["Repairs", "General Labor"],
    icon: Wrench,
    headerGradient: "from-amber-500 to-amber-700",
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-400",
    glowColor: "shadow-amber-500/40",
    ringColor: "ring-amber-500",
    crew: [1, 2],
    duration: [1, 6],
    earn: [75, 400],
    description: "General repairs, installs & odd jobs handled",
  },
  {
    key: "flooring",
    label: "Flooring",
    tags: ["Install", "Refinish"],
    icon: Layers,
    headerGradient: "from-teal-500 to-teal-700",
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-400",
    glowColor: "shadow-teal-500/40",
    ringColor: "ring-teal-500",
    crew: [2, 3],
    duration: [3, 8],
    earn: [200, 600],
    description: "Hardwood, vinyl, laminate — install & removal",
  },
  {
    key: "painting",
    label: "Painting",
    tags: ["Interior", "Exterior"],
    icon: PaintBucket,
    headerGradient: "from-rose-500 to-rose-700",
    iconBg: "bg-rose-500/10",
    iconColor: "text-rose-400",
    glowColor: "shadow-rose-500/40",
    ringColor: "ring-rose-500",
    crew: [1, 3],
    duration: [2, 8],
    earn: [150, 600],
    description: "Fresh coats inside & out — clean, crisp finish",
  },
  {
    key: "lawn_care",
    label: "Lawn Care",
    tags: ["Mowing", "Trimming"],
    icon: Leaf,
    headerGradient: "from-green-500 to-green-700",
    iconBg: "bg-green-500/10",
    iconColor: "text-green-400",
    glowColor: "shadow-green-500/40",
    ringColor: "ring-green-500",
    crew: [1, 2],
    duration: [1, 3],
    earn: [50, 200],
    description: "Mowing, trimming & more — lawn kept sharp",
    status: "coming-soon",
  },
  {
    key: "window_cleaning",
    label: "Window Cleaning",
    tags: ["Streak-Free", "Residential"],
    icon: Droplets,
    headerGradient: "from-sky-500 to-sky-700",
    iconBg: "bg-sky-500/10",
    iconColor: "text-sky-400",
    glowColor: "shadow-sky-500/40",
    ringColor: "ring-sky-500",
    crew: [1, 2],
    duration: [1, 4],
    earn: [50, 250],
    description: "Crystal-clear panes — streak-free guarantee",
  },
  {
    key: "trash_valet",
    label: "Trash Valet",
    tags: ["Weekly", "Curbside"],
    icon: RefreshCcw,
    headerGradient: "from-emerald-500 to-emerald-700",
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-400",
    glowColor: "shadow-emerald-500/40",
    ringColor: "ring-emerald-500",
    crew: [1, 1],
    duration: [0, 1],
    earn: [30, 75],
    description: "We pull your bins — you never touch the cans",
  },
  {
    key: "custom",
    label: "Something Else",
    tags: ["Custom", "Get a Quote"],
    icon: HelpCircle,
    headerGradient: "from-violet-500 to-violet-700",
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-400",
    glowColor: "shadow-violet-500/40",
    ringColor: "ring-violet-500",
    crew: [1, 4],
    duration: [1, 8],
    earn: [50, 500],
    description: "Describe what you need — we'll build a quote",
  },
  {
    key: "cleaning",
    label: "Move Cleaning",
    tags: ["Move-In", "Move-Out"],
    icon: Sparkles,
    headerGradient: "from-purple-500 to-purple-700",
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-400",
    glowColor: "shadow-purple-500/40",
    ringColor: "ring-purple-500",
    crew: [1, 3],
    duration: [2, 6],
    earn: [100, 400],
    description: "Deep clean for move-in & move-out days",
  },
  {
    key: "demolition",
    label: "Light Demo",
    tags: ["Tearout", "Cleanout"],
    icon: HardHat,
    headerGradient: "from-red-500 to-red-700",
    iconBg: "bg-red-500/10",
    iconColor: "text-red-400",
    glowColor: "shadow-red-500/40",
    ringColor: "ring-red-500",
    crew: [2, 4],
    duration: [2, 8],
    earn: [200, 600],
    description: "Demo, tearout & cleanout — we haul the debris",
  },
  {
    key: "roofing",
    label: "Roofing",
    tags: ["Repair", "Replacement"],
    icon: Home,
    headerGradient: "from-stone-500 to-stone-700",
    iconBg: "bg-stone-500/10",
    iconColor: "text-stone-400",
    glowColor: "shadow-stone-500/40",
    ringColor: "ring-stone-500",
    crew: [2, 4],
    duration: [3, 8],
    earn: [300, 800],
    description: "Shingle repair & full replacement — done right",
  },
  {
    key: "labor",
    label: "Labor Only",
    tags: ["By the Hour", "General Help"],
    icon: Wrench,
    headerGradient: "from-amber-400 to-yellow-600",
    iconBg: "bg-yellow-500/10",
    iconColor: "text-yellow-400",
    glowColor: "shadow-yellow-500/40",
    ringColor: "ring-yellow-500",
    crew: [1, 4],
    duration: [2, 8],
    earn: [100, 500],
    description: "Helpers by the hour — loading, lifting & more",
  },
];

export function getService(key: string): ServiceConfig | undefined {
  return SERVICES.find(s => s.key === key);
}
