import { db } from './db';
import { rewardCategories, rewardItems } from '@shared/schema';
import { eq, sql } from 'drizzle-orm';

const CATEGORIES = [
  { name: "Quick Rewards", icon: "⚡", color: "#f59e0b", sortOrder: 1 },
  { name: "Service Credits", icon: "🛠️", color: "#3b82f6", sortOrder: 2 },
  { name: "Premium Rewards", icon: "👑", color: "#8b5cf6", sortOrder: 3 },
  { name: "Local Deals", icon: "🏘️", color: "#10b981", sortOrder: 4 },
  { name: "Seasonal Specials", icon: "🌟", color: "#ef4444", sortOrder: 5 },
  { name: "Digital & Fun", icon: "🎮", color: "#ec4899", sortOrder: 6 },
];

export async function seedRewardShop() {
  try {
    const existing = await db.select({ count: sql<number>`count(*)` }).from(rewardCategories);
    if (Number(existing[0]?.count) > 0) {
      console.log("✅ Reward shop already seeded — skipping");
      return;
    }

    console.log("🌱 Seeding JCMOVES Rewards Marketplace...");

    const cats = await db.insert(rewardCategories).values(CATEGORIES).returning();
    const catMap: Record<string, number> = {};
    for (const c of cats) catMap[c.name] = c.id;

    const ITEMS = [
      // ── Quick Rewards ──
      {
        categoryId: catMap["Quick Rewards"],
        name: "$5 Coffee Gift Card",
        shortDesc: "Redeem for a $5 coffee gift card",
        fullDesc: "Enjoy a $5 gift card for your favorite local coffee shop. Delivered digitally within 24 hours.",
        tokenPrice: 250,
        cashValue: "5.00",
        status: "active",
        featured: true,
        deliveryType: "digital_code",
        promoBadge: "Most Popular",
        adminNotes: "Issue via digital gift card. Contact customer within 24h.",
      },
      {
        categoryId: catMap["Quick Rewards"],
        name: "Priority Support Text Line",
        shortDesc: "24-hour priority text support access",
        fullDesc: "Get direct text line access to our crew for any moving or junk removal questions for 24 hours.",
        tokenPrice: 300,
        cashValue: "3.00",
        status: "active",
        deliveryType: "manual",
        adminNotes: "Send user our priority text number.",
      },
      {
        categoryId: catMap["Quick Rewards"],
        name: "Moving Supply Discount",
        shortDesc: "10% off boxes, tape & packing supplies",
        fullDesc: "10% discount code on any moving supply purchase. Applies to boxes, tape, bubble wrap, and packing paper.",
        tokenPrice: 500,
        cashValue: "8.00",
        status: "active",
        deliveryType: "digital_code",
        adminNotes: "Generate promo code for 10% off supplies.",
      },
      {
        categoryId: catMap["Quick Rewards"],
        name: "Free Estimate Bonus",
        shortDesc: "Priority same-day estimate scheduling",
        fullDesc: "Get your moving or junk removal estimate scheduled same-day instead of waiting. Jump to the front of the queue.",
        tokenPrice: 750,
        cashValue: "10.00",
        status: "active",
        deliveryType: "schedule_required",
        scheduleRequired: true,
        adminNotes: "Mark their estimate request as priority in the pipeline.",
      },

      // ── Service Credits ──
      {
        categoryId: catMap["Service Credits"],
        name: "15-Minute Labor Credit",
        shortDesc: "15 minutes of extra moving help",
        fullDesc: "Add 15 minutes of crew labor to your next service booking. Great for those extra tasks like appliance repositioning or last-minute carries.",
        tokenPrice: 1000,
        cashValue: "15.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 60,
        maxPerUser: 4,
        maxPerMonth: 2,
        promoBadge: "Best Value",
        adminNotes: "Apply 15-min credit to their next service invoice.",
      },
      {
        categoryId: catMap["Service Credits"],
        name: "30-Minute Labor Credit",
        shortDesc: "Half hour of extra crew assistance",
        fullDesc: "30 minutes of professional moving crew labor. Use it on your next booking for any task — carrying, loading, or setup.",
        tokenPrice: 2500,
        cashValue: "30.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 90,
        maxPerUser: 3,
        maxPerMonth: 1,
        adminNotes: "Apply 30-min labor credit to invoice.",
      },
      {
        categoryId: catMap["Service Credits"],
        name: "Junk Removal Add-On Discount",
        shortDesc: "$15 off your next junk removal job",
        fullDesc: "Save $15 on your next scheduled junk removal. Works for garage cleanouts, single items, curbside pickup, or full hauls.",
        tokenPrice: 1250,
        cashValue: "15.00",
        status: "active",
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 60,
        adminNotes: "Deduct $15 from next junk removal invoice.",
      },
      {
        categoryId: catMap["Service Credits"],
        name: "Furniture Rearrange Visit",
        shortDesc: "In-home furniture repositioning session",
        fullDesc: "One crew member will come rearrange furniture in a single room. No moving truck needed — just heavy lifting.",
        tokenPrice: 10000,
        cashValue: "75.00",
        status: "active",
        deliveryType: "schedule_required",
        scheduleRequired: true,
        expirationDays: 90,
        maxPerUser: 2,
        maxPerMonth: 1,
        tierRequired: "bronze",
        adminNotes: "Schedule with one crew member. 30-45 min visit.",
      },
      {
        categoryId: catMap["Service Credits"],
        name: "Priority Booking Upgrade",
        shortDesc: "Move your service to priority scheduling",
        fullDesc: "Skip the wait and get your moving or junk removal service scheduled in the next available priority slot.",
        tokenPrice: 750,
        cashValue: "20.00",
        status: "active",
        deliveryType: "manual",
        scheduleRequired: false,
        expirationDays: 30,
        adminNotes: "Move their booking request to priority queue.",
      },
      {
        categoryId: catMap["Service Credits"],
        name: "$25 Off Moving Service",
        shortDesc: "$25 discount on any moving job",
        fullDesc: "Apply a $25 credit toward any moving service — local move, long-distance, or commercial. No minimum required.",
        tokenPrice: 5000,
        cashValue: "25.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 120,
        adminNotes: "Deduct $25 from invoice. Note redemption ID.",
      },

      // ── Premium Rewards ──
      {
        categoryId: catMap["Premium Rewards"],
        name: "1-Hour Labor Credit",
        shortDesc: "Full hour of professional moving crew help",
        fullDesc: "One full hour of moving crew assistance. Use it on any service — loading, unloading, packing assistance, or heavy item handling.",
        tokenPrice: 20000,
        cashValue: "100.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 120,
        maxPerUser: 2,
        maxPerMonth: 1,
        tierRequired: "bronze",
        promoBadge: "🔥 Top Reward",
        adminNotes: "Apply 1-hour crew credit to their invoice.",
      },
      {
        categoryId: catMap["Premium Rewards"],
        name: "$25 Gas or Grocery Card",
        shortDesc: "$25 gift card for gas or groceries",
        fullDesc: "Choose between a $25 gas station card or $25 grocery store card. Delivered digitally or by mail within 48 hours.",
        tokenPrice: 12500,
        cashValue: "25.00",
        status: "active",
        deliveryType: "manual",
        expirationDays: 365,
        tierRequired: "bronze",
        adminNotes: "Contact user for gas vs grocery preference. Issue card within 48h.",
      },
      {
        categoryId: catMap["Premium Rewards"],
        name: "$50 Local Gift Card",
        shortDesc: "$50 gift card to a local business",
        fullDesc: "A $50 gift card to a local business of your choice — restaurant, coffee shop, hardware store, or other partners.",
        tokenPrice: 50000,
        cashValue: "50.00",
        status: "active",
        deliveryType: "manual",
        expirationDays: 365,
        maxPerUser: 1,
        maxPerMonth: 1,
        tierRequired: "silver",
        adminNotes: "Coordinate with user. Must have Silver tier.",
      },
      {
        categoryId: catMap["Premium Rewards"],
        name: "Half-Day Moving Discount",
        shortDesc: "$75 off a half-day moving job",
        fullDesc: "Save $75 on any half-day move (4-hour crew booking). Ideal for apartment moves, single-room relocations, or storage unit jobs.",
        tokenPrice: 30000,
        cashValue: "75.00",
        status: "active",
        deliveryType: "service_credit",
        scheduleRequired: true,
        expirationDays: 120,
        maxPerUser: 1,
        maxPerMonth: 1,
        tierRequired: "silver",
        promoBadge: "High Value",
        adminNotes: "Apply $75 discount to 4+ hour move invoice.",
      },
      {
        categoryId: catMap["Premium Rewards"],
        name: "VIP Customer Bundle",
        shortDesc: "Priority booking + 1hr credit + gift card",
        fullDesc: "The full VIP package: priority scheduling for one year, $50 service credit, and a $25 local gift card. For our most loyal customers.",
        tokenPrice: 100000,
        cashValue: "150.00",
        status: "active",
        deliveryType: "manual",
        scheduleRequired: false,
        expirationDays: 365,
        maxPerUser: 1,
        maxPerMonth: 1,
        tierRequired: "gold",
        promoBadge: "⭐ VIP",
        adminNotes: "High-value redemption. Confirm with Darrell before issuing.",
      },

      // ── Seasonal Specials ──
      {
        categoryId: catMap["Seasonal Specials"],
        name: "Snow Removal Touch-Up",
        shortDesc: "One driveway/walkway snow clearing",
        fullDesc: "Quick snow shoveling service for one driveway or walkway path. Includes salting. Perfect for elderly neighbors or busy families.",
        tokenPrice: 7500,
        cashValue: "60.00",
        status: "active",
        featured: true,
        deliveryType: "schedule_required",
        scheduleRequired: true,
        expirationDays: 90,
        maxPerUser: 2,
        isLimitedTime: true,
        promoBadge: "❄️ Winter",
        adminNotes: "Schedule with snow removal crew. Winter months only.",
      },
      {
        categoryId: catMap["Seasonal Specials"],
        name: "Yard Debris Bag Pickup",
        shortDesc: "Curbside yard waste pickup service",
        fullDesc: "We pick up up to 5 yard waste bags from your property — leaves, branches, clippings, or debris. Spring and fall special.",
        tokenPrice: 3000,
        cashValue: "35.00",
        status: "active",
        deliveryType: "schedule_required",
        scheduleRequired: true,
        expirationDays: 60,
        maxPerUser: 3,
        isLimitedTime: true,
        promoBadge: "🍂 Seasonal",
        adminNotes: "Seasonal offer. Check availability before confirming.",
      },

      // ── Digital & Fun ──
      {
        categoryId: catMap["Digital & Fun"],
        name: "Spin Wheel Entry",
        shortDesc: "One free spin on the JCMOVES prize wheel",
        fullDesc: "Enter the JCMOVES prize spin wheel. Prizes include token multipliers, service discounts, mystery boxes, and bonus claims.",
        tokenPrice: 100,
        cashValue: "1.00",
        status: "active",
        featured: true,
        deliveryType: "digital_code",
        maxPerUser: 10,
        maxPerMonth: 5,
        promoBadge: "🎰 Fun",
        adminNotes: "Issue spin entry via the prize wheel system.",
      },
      {
        categoryId: catMap["Digital & Fun"],
        name: "Bonus Faucet Claim",
        shortDesc: "Extra JCMOVES faucet claim today",
        fullDesc: "Get one extra faucet claim today on top of your normal daily limit. Stack tokens faster.",
        tokenPrice: 200,
        cashValue: "2.00",
        status: "active",
        deliveryType: "digital_code",
        maxPerUser: 3,
        maxPerMonth: 5,
        adminNotes: "Credit extra faucet claim to user wallet manually.",
      },
      {
        categoryId: catMap["Digital & Fun"],
        name: "Mystery Reward Box",
        shortDesc: "Surprise reward — worth 500–5000 JCMOVES",
        fullDesc: "Open a mystery reward box and receive a surprise token bonus or service perk. Could be tokens, a service add-on, or a gift card.",
        tokenPrice: 350,
        cashValue: "5.00",
        status: "active",
        deliveryType: "manual",
        maxPerUser: 5,
        maxPerMonth: 2,
        promoBadge: "🎁 Mystery",
        adminNotes: "Surprise the user with a random reward from the catalog or bonus tokens.",
      },
      {
        categoryId: catMap["Digital & Fun"],
        name: "Loyalty Tier Boost",
        shortDesc: "Accelerate your tier progress",
        fullDesc: "Get a 500 JCMOVES bonus added directly to your account to help reach your next loyalty tier faster.",
        tokenPrice: 150,
        cashValue: "2.50",
        status: "active",
        deliveryType: "digital_code",
        maxPerUser: 3,
        maxPerMonth: 1,
        adminNotes: "Credit 500 JCMOVES to their wallet as tier boost.",
      },
    ];

    await db.insert(rewardItems).values(ITEMS as any);
    console.log(`✅ Seeded ${CATEGORIES.length} categories and ${ITEMS.length} reward items`);
  } catch (err) {
    console.error("Error seeding reward shop:", err);
  }
}
