import { db } from './db';
import { rewardCategories, rewardItems } from '@shared/schema';
import { sql } from 'drizzle-orm';

const CATEGORIES = [
  { name: "☕ Entry Tier",       icon: "☕", color: "#78350f", sortOrder: 1 },
  { name: "🎟️ Discount Coupons", icon: "🎟️", color: "#7c3aed", sortOrder: 2 },
  { name: "🛠️ Service Credits",  icon: "🛠️", color: "#1d4ed8", sortOrder: 3 },
  { name: "🎁 Gift Cards",       icon: "🎁", color: "#065f46", sortOrder: 4 },
  { name: "⚡ Quantum Spin",     icon: "⚡", color: "#b45309", sortOrder: 5 },
];

export async function seedRewardShop() {
  try {
    const existing = await db.select({ count: sql<number>`count(*)` }).from(rewardCategories);
    if (Number(existing[0]?.count) > 0) {
      console.log("✅ Reward shop already seeded — skipping");
      return;
    }

    console.log("🌱 Seeding JCMOVES Rewards Marketplace...");

    const cats = await db.insert(rewardCategories).values(CATEGORIES).returning();
    const catMap: Record<string, number> = {};
    for (const c of cats) catMap[c.name] = c.id;

    const ITEMS = [
      // ── ☕ Entry Tier ── (Spend $100 → earn ~5,000 JCMOVES → redeem)
      {
        categoryId: catMap["☕ Entry Tier"],
        name: "Copper Cup Coffee — $5 Gift Card",
        shortDesc: "A $5 gift card to Copper Cup Coffee in Ironwood, MI",
        fullDesc: "You've earned it! Redeem just 250 JCMOVES for a $5 gift card to Copper Cup Coffee — your local coffee spot right here in Ironwood. Choose free local pickup or have it delivered.",
        tokenPrice: 250,
        cashValue: "5.00",
        status: "active",
        featured: true,
        inventory: 50,
        deliveryType: "manual",
        requiresApproval: true,
        expirationDays: 365,
        promoBadge: "Most Popular",
        fulfillmentNote: "After redeeming, choose FREE local pickup in Ironwood, MI — or add a note requesting home delivery (1,000 JCMOVES extra, admin will confirm). We'll contact you within 24 hours to arrange.",
        adminNotes: "Issue $5 Copper Cup gift card. Ask customer: free local pickup in Ironwood OR ship to home (charge 1,000 extra JCMOVES). Contact within 24 hours.",
      },

      // ── 🎟️ Discount Coupons ──
      {
        categoryId: catMap["🎟️ Discount Coupons"],
        name: "10% Off Your Next Service",
        shortDesc: "Auto-generated coupon — up to $25 off any job",
        fullDesc: "Spend $250 on your move, earn 12,500 JCMOVES, redeem for 10% off your next service — up to $25 in savings. A unique promo code is generated instantly and stored in your Redemptions tab so you can use it anytime.",
        tokenPrice: 12500,
        cashValue: "25.00",
        status: "active",
        featured: true,
        deliveryType: "digital_code",
        isInstant: true,
        createsCouponCode: true,
        couponDiscountPct: 10,
        couponMaxDiscount: "25.00",
        expirationDays: 365,
        promoBadge: "Instant Reward",
        fulfillmentNote: "Your unique promo code is generated immediately and saved to your Redemptions tab. Use it at checkout or give it to us when booking. Valid for 1 year — 10% off any service, up to $25.",
        adminNotes: "Promo code auto-generated by system. 10% off service discount, max $25. Check promo_codes table.",
      },
      {
        categoryId: catMap["🎟️ Discount Coupons"],
        name: "20% Off Your Next Service",
        shortDesc: "Auto-generated coupon — up to $50 off any job",
        fullDesc: "Hit the $400 service milestone, earn 20,000 JCMOVES, unlock 20% off your next job — up to $50 savings. Promo code generated instantly, valid for a full year.",
        tokenPrice: 20000,
        cashValue: "50.00",
        status: "active",
        featured: true,
        deliveryType: "digital_code",
        isInstant: true,
        createsCouponCode: true,
        couponDiscountPct: 20,
        couponMaxDiscount: "50.00",
        expirationDays: 365,
        promoBadge: "Best Deal",
        fulfillmentNote: "Your unique promo code is generated immediately and saved to your Redemptions tab. Valid for 1 year — 20% off any service, up to $50. Show us at booking or enter at checkout.",
        adminNotes: "Promo code auto-generated by system. 20% off service, max $50. Check promo_codes table.",
      },

      // ── 🛠️ Service Credits ──
      {
        categoryId: catMap["🛠️ Service Credits"],
        name: "$75 Off a Service",
        shortDesc: "Apply $75 directly off your next move or project",
        fullDesc: "Spend around $600 with us, accumulate 30,000 JCMOVES, and redeem for $75 off a future service. Great for a 3-mover, 3-hour job or any larger project. Our crew shows up — you save.",
        tokenPrice: 30000,
        cashValue: "75.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        createsInvoiceCredit: true,
        requiresSchedule: true,
        expirationDays: 180,
        promoBadge: "High Value",
        fulfillmentNote: "Book a service and mention your redemption. The $75 discount is applied to your invoice by our team. Redemption stays active for 6 months.",
        adminNotes: "Deduct $75 from service invoice. Reference redemption ID. Valid 180 days.",
      },
      {
        categoryId: catMap["🛠️ Service Credits"],
        name: "$100 Off a Job",
        shortDesc: "Get $100 off — let us take the stress off your back",
        fullDesc: "You've saved 40,000 JCMOVES — that's real loyalty. Redeem for $100 off any service. Perfect for that 2-mover, 1-hour job you've been putting off. Need something done? Need our crew to knock it out? This one's for you.",
        tokenPrice: 40000,
        cashValue: "100.00",
        status: "active",
        featured: true,
        deliveryType: "service_credit",
        createsInvoiceCredit: true,
        requiresSchedule: true,
        expirationDays: 180,
        promoBadge: "Top Pick",
        fulfillmentNote: "Book any service and the $100 is deducted from your invoice. Our team applies it when processing your job. Valid for 6 months from redemption.",
        adminNotes: "Apply $100 invoice credit. Confirm redemption ID. Valid 180 days.",
      },
      {
        categoryId: catMap["🛠️ Service Credits"],
        name: "$150 Off a Service",
        shortDesc: "Stack up 50,000 JCMOVES for $150 off any job",
        fullDesc: "You've been putting in the hard work collecting JCMOVES — and we want to repay the favor big. Redeem 50,000 JCMOVES for $150 off any future move or project. No minimum, no catch.",
        tokenPrice: 50000,
        cashValue: "150.00",
        status: "active",
        deliveryType: "service_credit",
        createsInvoiceCredit: true,
        requiresSchedule: true,
        expirationDays: 365,
        promoBadge: "Mega Discount",
        fulfillmentNote: "$150 applied to your next service invoice by our team. Valid for 1 year from redemption. Call or book online and mention your code.",
        adminNotes: "Deduct $150 from service invoice. Confirm with redemption ID.",
      },
      {
        categoryId: catMap["🛠️ Service Credits"],
        name: "Free 2 Movers · 2 Hours (Local)",
        shortDesc: "200,000 JCMOVES = 2 movers, 2 hours — free labor, you cover travel if needed",
        fullDesc: "The grand prize of loyalty. Redeem 200,000 JCMOVES and our 2-mover crew works for 2 hours at no labor charge. Perfect for local Ironwood area jobs. Longer distance? You cover travel time — but the labor is on us. Our way of saying thank you for everything.",
        tokenPrice: 200000,
        cashValue: "250.00",
        status: "active",
        deliveryType: "service_credit",
        createsInvoiceCredit: true,
        requiresSchedule: true,
        requiresApproval: true,
        expirationDays: 365,
        maxPerUser: 1,
        promoBadge: "⭐ Grand Prize",
        fulfillmentNote: "Schedule your job and mention this redemption. 2 movers, 2 hours of labor — free. Local Ironwood area: zero charge. Longer distance: travel time cost only. Admin approval required to confirm scheduling.",
        adminNotes: "GRAND PRIZE. Free 2-mover, 2-hour labor booking. Local = fully free. Longer distance = customer pays travel only. Confirm with Darrell before scheduling.",
      },

      // ── 🎁 Gift Cards ──
      {
        categoryId: catMap["🎁 Gift Cards"],
        name: "$20 Pizza Gift Card",
        shortDesc: "Domino's or Little Caesars — your choice",
        fullDesc: "Hit 40,000 JCMOVES and treat yourself to a $20 pizza gift card. You choose: Domino's or Little Caesars. We'll deliver the digital code or physical card based on your preference. You earned it.",
        tokenPrice: 40000,
        cashValue: "20.00",
        status: "active",
        deliveryType: "manual",
        requiresApproval: true,
        expirationDays: 365,
        promoBadge: "Fan Favorite",
        fulfillmentNote: "Admin contacts you within 24 hours to confirm: Domino's or Little Caesars. Digital code sent by email or text. Physical card available for local pickup.",
        adminNotes: "Contact customer: Domino's or Little Caesars? Issue $20 digital gift card or physical card. Confirm within 24 hours.",
      },
      {
        categoryId: catMap["🎁 Gift Cards"],
        name: "$35 Prepaid Visa Gift Card",
        shortDesc: "Use it anywhere Visa is accepted",
        fullDesc: "60,000 JCMOVES earns you a $35 Prepaid Visa gift card — spend it anywhere Visa is accepted. Gas, groceries, online shopping, you name it. Shipped to your address within 3-5 days.",
        tokenPrice: 60000,
        cashValue: "35.00",
        status: "active",
        deliveryType: "manual",
        requiresApproval: true,
        expirationDays: 365,
        promoBadge: "Spend Anywhere",
        fulfillmentNote: "Admin processes your request and ships a $35 Prepaid Visa card to your address within 3-5 business days. You'll receive a confirmation once shipped.",
        adminNotes: "Issue $35 Prepaid Visa. Get mailing address from customer. Ship within 3-5 business days.",
      },
      {
        categoryId: catMap["🎁 Gift Cards"],
        name: "$35 Gas Card",
        shortDesc: "Fill up on us — 60,000 JCMOVES well spent",
        fullDesc: "Redeem 60,000 JCMOVES for a $35 gas gift card. Works at most major gas stations. Physical card shipped to your address — because you've earned a full tank.",
        tokenPrice: 60000,
        cashValue: "35.00",
        status: "active",
        deliveryType: "manual",
        requiresApproval: true,
        expirationDays: 365,
        fulfillmentNote: "Admin ships your $35 gas card within 3-5 business days. We'll confirm which station card works best for your area.",
        adminNotes: "Issue $35 gas card. Confirm preferred gas station brand with customer. Ship within 3-5 days.",
      },
      {
        categoryId: catMap["🎁 Gift Cards"],
        name: "$75 Gas or Prepaid Visa Card",
        shortDesc: "Your choice — $75 to spend your way",
        fullDesc: "The ultimate 120,000 JCMOVES gift card redemption. You pick: a $75 gas card to keep your tank full, or a $75 Prepaid Visa to spend anywhere you want. Two options, one reward — earned through serious loyalty.",
        tokenPrice: 120000,
        cashValue: "75.00",
        status: "active",
        deliveryType: "manual",
        requiresApproval: true,
        expirationDays: 365,
        maxPerUser: 2,
        promoBadge: "Premium Reward",
        fulfillmentNote: "Admin contacts you to confirm: Gas Card or Prepaid Visa? Your $75 card ships within 3-5 business days after confirmation.",
        adminNotes: "HIGH VALUE. Contact customer: Gas Card or Prepaid Visa? Issue $75 accordingly. Ship 3-5 days. Confirm with Darrell for large batches.",
      },

      // ── ⚡ Quantum Spin ──
      {
        categoryId: catMap["⚡ Quantum Spin"],
        name: "Quantum Spin Entry",
        shortDesc: "One free spin on the Quantum Spin prize machine",
        fullDesc: "Buy one Quantum Spin entry from the marketplace and spin without spending directly from your wallet. Prizes include token jackpots, coupons, coffee gift cards, and mystery rewards. Jackpots grow every spin.",
        tokenPrice: 100,
        cashValue: "1.00",
        status: "active",
        featured: true,
        deliveryType: "digital_code",
        createsSpinCredit: true,
        isInstant: true,
        maxPerUser: 50,
        maxPerMonth: 20,
        promoBadge: "⚡ Instant",
        fulfillmentNote: "Your free spin credit is added instantly. Open the Quantum Spin wheel and it will appear automatically.",
        adminNotes: "Spin credit auto-issued via reward_entitlements. No manual action needed.",
      },
    ];

    await db.insert(rewardItems).values(ITEMS as any);
    console.log(`✅ Seeded ${CATEGORIES.length} categories and ${ITEMS.length} reward items`);
  } catch (err) {
    console.error("Error seeding reward shop:", err);
  }
}
