import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { createDailySpin,DAILY_SPIN_SCHEMA,consumeSpinCredit } from '../dailySpin';
const db=new PGlite();
await db.exec(`CREATE TABLE users(id VARCHAR PRIMARY KEY);INSERT INTO users VALUES('matt'),('evan'),('fail');
CREATE TABLE spin_config(setting_key TEXT PRIMARY KEY,setting_value TEXT);INSERT INTO spin_config VALUES('spin_wheel_enabled','true');
CREATE TABLE reward_entitlements(id SERIAL PRIMARY KEY,user_id VARCHAR,entitlement_type TEXT,value_json JSONB,status TEXT,expires_at TIMESTAMPTZ,consumed_at TIMESTAMPTZ,redemption_id INTEGER);
${DAILY_SPIN_SCHEMA}`);
let queue=Promise.resolve();
const query=async(text:string,values?:any[])=>db.query(text,values);
const pool={query,connect:async()=>{const before=queue;let release!:()=>void;queue=new Promise<void>(resolve=>release=resolve);await before;return {query,release};}} as any;
const daily=createDailySpin(pool);
assert.equal((await daily.status('matt')).canClaim,true);
const claims=await Promise.all([daily.claim('matt'),daily.claim('matt')]);
assert.equal(claims[0].entitlementId,claims[1].entitlementId);
assert.equal((await db.query('SELECT * FROM reward_entitlements')).rows.length,1);
assert.equal((await daily.status('matt')).available,true);
assert.equal(await consumeSpinCredit(pool,'evan',claims[0].entitlementId),false);
await db.exec('BEGIN');assert.equal(await consumeSpinCredit(pool,'matt',claims[0].entitlementId),true);await db.exec('ROLLBACK');
assert.equal((await daily.status('matt')).available,true,'failed spin must preserve credit');
assert.equal(await consumeSpinCredit(pool,'matt',claims[0].entitlementId),true);
assert.equal(await consumeSpinCredit(pool,'matt',claims[0].entitlementId),false,'a used daily spin cannot replay');
assert.equal((await daily.status('matt')).canClaim,false);
const expired=(await db.query<{id:number}>(`INSERT INTO reward_entitlements(user_id,entitlement_type,value_json,status,expires_at) VALUES('evan','spin_credit','{"spins":1}','active',NOW()-INTERVAL '1 second') RETURNING id`)).rows[0];
assert.equal(await consumeSpinCredit(pool,'evan',expired.id),false);
await db.exec(`CREATE FUNCTION reject_daily_claim() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.user_id='fail' THEN RAISE EXCEPTION 'Synthetic write failure'; END IF; RETURN NEW; END $$;
CREATE TRIGGER reject_daily_claim BEFORE INSERT ON daily_spin_claims FOR EACH ROW EXECUTE FUNCTION reject_daily_claim();`);
await assert.rejects(()=>daily.claim('fail'));
assert.equal((await db.query(`SELECT * FROM reward_entitlements WHERE user_id='fail'`)).rows.length,0,'failed claim cannot leave a free entitlement behind');
const dates=(await db.query<{spring:string;fall:string}>(`SELECT to_char((('2026-03-08'::date+1)::timestamp AT TIME ZONE 'America/Chicago') AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS') AS spring,to_char((('2026-11-01'::date+1)::timestamp AT TIME ZONE 'America/Chicago') AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS') AS fall`)).rows[0];
assert.match(dates.spring,/05:00:00/);assert.match(dates.fall,/06:00:00/);
await db.close();console.log('Daily spin idempotency, ownership, rollback, expiration and Chicago DST tests passed');

