import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const source=readFileSync(new URL('../reviewCelebrations.ts',import.meta.url),'utf8');
const migration=source.match(/export const REVIEW_CELEBRATION_SCHEMA=`([\s\S]*?)`;/)?.[1];
assert.ok(migration);
const db=new PGlite();
await db.exec(`CREATE TABLE users(id VARCHAR PRIMARY KEY);
CREATE TABLE leads(id VARCHAR PRIMARY KEY,crew_members TEXT[],accepted_by_employees TEXT[],assigned_to_user_id VARCHAR);
CREATE TABLE reviews(id VARCHAR PRIMARY KEY,lead_id VARCHAR,rating INTEGER);
CREATE TABLE review_tip_allocations(id VARCHAR PRIMARY KEY,review_id VARCHAR,status TEXT,payroll_paid_at TIMESTAMP);
INSERT INTO users VALUES('matt'),('evan');
INSERT INTO leads VALUES('job',ARRAY['matt','evan'],ARRAY['matt'],'matt');`);
await db.exec(migration);
await db.exec(migration);
await db.exec(`BEGIN;INSERT INTO reviews VALUES('rollback','job',5);ROLLBACK;`);
assert.equal((await db.query('SELECT * FROM review_celebration_outbox')).rows.length,0,'rolled back reviews cannot celebrate');
await db.exec(`INSERT INTO reviews VALUES('review','job',5)`);
const initial=await db.query<{crew_ids:string[]}>('SELECT crew_ids FROM review_celebration_outbox');
assert.deepEqual(initial.rows[0].crew_ids.sort(),['evan','matt'],'snapshot assigned movers exactly once');
await db.exec(`INSERT INTO review_tip_allocations VALUES('tip','review','pending_payment',NULL);
UPDATE review_tip_allocations SET status='confirmed' WHERE id='tip';
UPDATE review_tip_allocations SET status='confirmed' WHERE id='tip';`);
assert.equal((await db.query('SELECT * FROM review_celebration_outbox')).rows.length,2,'one update per actual tip state transition');
await db.exec(`BEGIN;UPDATE review_tip_allocations SET payroll_paid_at='2026-09-15' WHERE id='tip';ROLLBACK;`);
assert.equal((await db.query('SELECT * FROM review_celebration_outbox')).rows.length,2,'rolled back payout cannot celebrate');
await db.exec(`INSERT INTO review_worker_thanks VALUES('review','matt',NOW()) ON CONFLICT DO NOTHING;INSERT INTO review_worker_thanks VALUES('review','matt',NOW()) ON CONFLICT DO NOTHING;`);
assert.equal((await db.query('SELECT * FROM review_worker_thanks')).rows.length,1);
await db.close();
console.log('Review celebration migration, rollback, tip transition and thanks deduplication passed');
