export {
  JC_TRUCK_EXTRA_MILE_RATE,
  JC_TRUCK_15_FT_RENTAL_FEE,
  JC_TRUCK_26_FT_RENTAL_FEE,
  JC_TRUCK_INCLUDED_MILES,
  JC_TRUCK_LOCAL_RENTAL_FEE,
  JC_TRUCK_OUT_OF_TOWN_RENTAL_FEE,
  JC_TRUCK_FAR_OUT_OF_TOWN_RENTAL_FEE,
  calculateJcTruckRentalFee,
} from "./movingPricing";
