import type { MarketplaceRequestShapeId } from "./marketplaceShapes";

export type ServicePriceMenuCategoryId = "delivery" | "moving" | "repeat" | "projects";

export type ServicePriceMenuTask = {
  id: string;
  categoryId: ServicePriceMenuCategoryId;
  serviceCode: string;
  shapeId: MarketplaceRequestShapeId;
  label: string;
  description: string;
  priceMin: number;
  priceMax: number;
  priceUnit: string;
  defaultCrew: number;
  defaultHours: number;
  jobSize: "small" | "medium" | "large" | "quote_review";
  loadType?: string;
  movingPath?: "tiny_items" | "load_only" | "unload_only" | "load_unload" | "full_household" | "heavy_specialty" | "packing_assembly";
  tags: string[];
  customerNeeds: string[];
  operationsSignal: string;
};

export const SERVICE_PRICE_MENU_CATEGORIES: Array<{
  id: ServicePriceMenuCategoryId;
  label: string;
  summary: string;
}> = [
  { id: "delivery", label: "Delivery + Small Project", summary: "Single items, store pickups, disposal, short work blocks." },
  { id: "moving", label: "Moving Help", summary: "Load, unload, both, containers, heavy items, apartment help." },
  { id: "repeat", label: "Repeat Loop Jobs", summary: "Lawn, snow, junk, handyman, and recurring route work." },
  { id: "projects", label: "Projects + Trades", summary: "Handyman, roofing, flooring, painting, and light demo." },
];

export const SERVICE_PRICE_MENU: ServicePriceMenuTask[] = [
  {
    id: "single_item_delivery",
    categoryId: "delivery",
    serviceCode: "delivery",
    shapeId: "delivery_reuse",
    label: "Single item delivery",
    description: "One furniture, appliance, or boxed item picked up and dropped off.",
    priceMin: 125,
    priceMax: 300,
    priceUnit: "typical minimum",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    tags: ["single item", "furniture", "appliance"],
    customerNeeds: ["pickup address", "drop-off address", "item photo", "preferred date"],
    operationsSignal: "Confirm item size, stairs, drive time, and whether one truck run covers it.",
  },
  {
    id: "store_pickup",
    categoryId: "delivery",
    serviceCode: "delivery",
    shapeId: "delivery_reuse",
    label: "Store pickup delivery",
    description: "Pickup from a store, marketplace seller, or curbside order.",
    priceMin: 150,
    priceMax: 350,
    priceUnit: "pickup run",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    tags: ["store pickup", "marketplace", "curbside"],
    customerNeeds: ["store or pickup address", "drop-off address", "order size", "pickup window"],
    operationsSignal: "Check pickup timing, loading help, item dimensions, and route fit.",
  },
  {
    id: "appliance_delivery",
    categoryId: "delivery",
    serviceCode: "delivery",
    shapeId: "delivery_reuse",
    label: "Appliance delivery",
    description: "Washer, dryer, fridge, stove, freezer, or similar heavy delivery.",
    priceMin: 175,
    priceMax: 450,
    priceUnit: "item run",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "medium",
    tags: ["appliance", "heavy item", "delivery"],
    customerNeeds: ["item photo", "pickup/drop-off", "stairs", "old item removal yes/no"],
    operationsSignal: "Flag appliance weight, stairs, hookups, disposal, and door clearance.",
  },
  {
    id: "donation_or_dump_run",
    categoryId: "delivery",
    serviceCode: "donation_dump_pickup",
    shapeId: "delivery_reuse",
    label: "Donation or dump run",
    description: "Small disposal, donation drop-off, or reuse run.",
    priceMin: 170,
    priceMax: 450,
    priceUnit: "small load",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    tags: ["junk", "donation", "dump run"],
    customerNeeds: ["item photos", "load size", "address", "dispose or donate"],
    operationsSignal: "Separate dump fee, donation proof, item count, and route stop.",
  },
  {
    id: "small_project_block",
    categoryId: "delivery",
    serviceCode: "small_project_labor",
    shapeId: "delivery_reuse",
    label: "Small project labor block",
    description: "A short two-person work block for lifting, carrying, staging, or setup.",
    priceMin: 300,
    priceMax: 600,
    priceUnit: "2-person block",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    tags: ["labor", "setup", "short project"],
    customerNeeds: ["address", "photos", "task list", "preferred date"],
    operationsSignal: "Confirm whether tools, truck, disposal, or specialty handling are needed.",
  },
  {
    id: "load_truck",
    categoryId: "moving",
    serviceCode: "moving",
    shapeId: "moving_help",
    label: "Load a truck",
    description: "Customer has a rental truck, trailer, POD, or container and needs loading help.",
    priceMin: 425,
    priceMax: 600,
    priceUnit: "2 movers / 2 hr min",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    loadType: "Load only",
    movingPath: "load_only",
    tags: ["load", "u-haul", "pods"],
    customerNeeds: ["address", "truck/container size", "stairs", "date/time"],
    operationsSignal: "Confirm truck size, access, stairs, and whether pads/straps are provided.",
  },
  {
    id: "unload_truck",
    categoryId: "moving",
    serviceCode: "moving",
    shapeId: "moving_help",
    label: "Unload a truck",
    description: "Unload a rental truck, trailer, POD, or storage container.",
    priceMin: 425,
    priceMax: 600,
    priceUnit: "2 movers / 2 hr min",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    loadType: "Unload only",
    movingPath: "unload_only",
    tags: ["unload", "u-haul", "storage"],
    customerNeeds: ["address", "truck/container size", "stairs", "date/time"],
    operationsSignal: "Confirm unload address, access path, stairs, elevator, and heavy items.",
  },
  {
    id: "load_and_unload",
    categoryId: "moving",
    serviceCode: "moving",
    shapeId: "moving_help",
    label: "Load and unload",
    description: "Moving help at both ends with a crew and time block.",
    priceMin: 850,
    priceMax: 1200,
    priceUnit: "3-4 movers / 3-4 hr target",
    defaultCrew: 3,
    defaultHours: 4,
    jobSize: "medium",
    loadType: "Both - load AND unload",
    movingPath: "load_unload",
    tags: ["moving", "load", "unload"],
    customerNeeds: ["origin", "drop-off address", "truck size", "date/time"],
    operationsSignal: "Confirm travel, crew count, drive time, stairs, and route-day eligibility.",
  },
  {
    id: "container_help",
    categoryId: "moving",
    serviceCode: "moving",
    shapeId: "moving_help",
    label: "POD / U-Box / container help",
    description: "Load, unload, or rearrange a storage container.",
    priceMin: 425,
    priceMax: 900,
    priceUnit: "container labor",
    defaultCrew: 2,
    defaultHours: 3,
    jobSize: "medium",
    loadType: "Load or unload container",
    movingPath: "load_unload",
    tags: ["pods", "u-box", "container"],
    customerNeeds: ["container count", "address", "access notes", "date/time"],
    operationsSignal: "Flag container placement, parking, ramp distance, and weather risk.",
  },
  {
    id: "heavy_item_move",
    categoryId: "moving",
    serviceCode: "moving",
    shapeId: "moving_help",
    label: "Heavy item move",
    description: "Safe, piano, treadmill, gun safe, appliance, or specialty item.",
    priceMin: 250,
    priceMax: 850,
    priceUnit: "quote review",
    defaultCrew: 3,
    defaultHours: 2,
    jobSize: "quote_review",
    loadType: "Heavy item",
    movingPath: "heavy_specialty",
    tags: ["heavy", "specialty", "stairs"],
    customerNeeds: ["item photo", "weight if known", "stairs", "pickup/drop-off"],
    operationsSignal: "Require photo and risk review before confirming crew and price.",
  },
  {
    id: "lawn_one_time",
    categoryId: "repeat",
    serviceCode: "lawn_care",
    shapeId: "repeat_loop",
    label: "Lawn care visit",
    description: "Mowing, trimming, cleanup, or one-time yard work.",
    priceMin: 85,
    priceMax: 250,
    priceUnit: "visit",
    defaultCrew: 2,
    defaultHours: 1,
    jobSize: "small",
    tags: ["lawn", "yard", "route"],
    customerNeeds: ["address", "yard photos", "frequency", "preferred day"],
    operationsSignal: "Capture route fit, yard size, gates, slope, and repeat potential.",
  },
  {
    id: "snow_event",
    categoryId: "repeat",
    serviceCode: "snow_removal",
    shapeId: "repeat_loop",
    label: "Snow removal visit",
    description: "Driveway, walkway, or storm cleanup.",
    priceMin: 75,
    priceMax: 400,
    priceUnit: "event",
    defaultCrew: 2,
    defaultHours: 1,
    jobSize: "small",
    tags: ["snow", "shovel", "plow"],
    customerNeeds: ["address", "driveway photos", "trigger depth", "repeat yes/no"],
    operationsSignal: "Capture route, trigger depth, obstacles, ice, and prepaid/repeat status.",
  },
  {
    id: "recurring_junk_pickup",
    categoryId: "repeat",
    serviceCode: "junk_removal",
    shapeId: "repeat_loop",
    label: "Repeat junk pickup",
    description: "Garage, rental, business, or recurring cleanout pickup.",
    priceMin: 170,
    priceMax: 600,
    priceUnit: "pickup",
    defaultCrew: 2,
    defaultHours: 2,
    jobSize: "small",
    tags: ["junk", "recurring", "cleanout"],
    customerNeeds: ["photos", "pickup frequency", "access notes", "preferred day"],
    operationsSignal: "Track repeat source, volume trend, disposal cost, and route day.",
  },
  {
    id: "handyman_loop",
    categoryId: "repeat",
    serviceCode: "handyman",
    shapeId: "repeat_loop",
    label: "Handyman repeat list",
    description: "Small repairs, installs, punch-list work, or property upkeep.",
    priceMin: 170,
    priceMax: 680,
    priceUnit: "task block",
    defaultCrew: 1,
    defaultHours: 2,
    jobSize: "small",
    tags: ["handyman", "repair", "repeat"],
    customerNeeds: ["task list", "photos", "materials needed", "preferred day"],
    operationsSignal: "Separate labor, materials, tool needs, and future repeat schedule.",
  },
  {
    id: "handyman_small_repair",
    categoryId: "projects",
    serviceCode: "handyman",
    shapeId: "repeat_loop",
    label: "Handyman small repair",
    description: "Doors, trim, patching, fixtures, assembly, mounting, or minor repair.",
    priceMin: 150,
    priceMax: 450,
    priceUnit: "small repair",
    defaultCrew: 1,
    defaultHours: 2,
    jobSize: "small",
    tags: ["handyman", "repair", "assembly"],
    customerNeeds: ["photos", "task list", "materials status", "address"],
    operationsSignal: "Confirm materials, tool needs, ladder height, and whether a second helper is needed.",
  },
  {
    id: "handyman_half_day",
    categoryId: "projects",
    serviceCode: "handyman",
    shapeId: "repeat_loop",
    label: "Handyman half-day block",
    description: "Bundle multiple small tasks into one work block.",
    priceMin: 300,
    priceMax: 700,
    priceUnit: "half day",
    defaultCrew: 1,
    defaultHours: 4,
    jobSize: "medium",
    tags: ["handyman", "punch list", "property"],
    customerNeeds: ["task list", "photos", "priority order", "materials status"],
    operationsSignal: "Rank task list, quote labor block, and separate materials from labor.",
  },
  {
    id: "light_demo_small",
    categoryId: "projects",
    serviceCode: "demolition",
    shapeId: "repeat_loop",
    label: "Light demo small tear-out",
    description: "Small cabinet, carpet, paneling, shed, fixture, or debris tear-out.",
    priceMin: 300,
    priceMax: 800,
    priceUnit: "small demo",
    defaultCrew: 2,
    defaultHours: 3,
    jobSize: "medium",
    tags: ["light demo", "tear-out", "debris"],
    customerNeeds: ["photos", "material type", "dump/disposal needed", "access"],
    operationsSignal: "Flag disposal, dust, shutoffs, hidden utilities, and PPE needs.",
  },
  {
    id: "light_demo_room",
    categoryId: "projects",
    serviceCode: "demolition",
    shapeId: "repeat_loop",
    label: "Room demo / cleanout",
    description: "Bigger tear-out, room prep, flooring removal, or cleanout with debris.",
    priceMin: 750,
    priceMax: 1800,
    priceUnit: "quote review",
    defaultCrew: 3,
    defaultHours: 4,
    jobSize: "large",
    tags: ["demo", "floor removal", "cleanout"],
    customerNeeds: ["photos", "room size", "material type", "disposal details"],
    operationsSignal: "Needs quote review for disposal, labor hours, tools, and risk.",
  },
  {
    id: "flooring_repair",
    categoryId: "projects",
    serviceCode: "flooring",
    shapeId: "repeat_loop",
    label: "Flooring repair / small install",
    description: "Patch, plank replacement, trim, threshold, or small room flooring.",
    priceMin: 300,
    priceMax: 1500,
    priceUnit: "flooring task",
    defaultCrew: 2,
    defaultHours: 3,
    jobSize: "medium",
    tags: ["flooring", "vinyl plank", "repair"],
    customerNeeds: ["photos", "square feet", "material type", "materials provided yes/no"],
    operationsSignal: "Capture sqft, floor type, prep/removal, transition pieces, and materials.",
  },
  {
    id: "flooring_install",
    categoryId: "projects",
    serviceCode: "flooring",
    shapeId: "repeat_loop",
    label: "Flooring install",
    description: "LVP, laminate, tile prep, old floor removal, or multi-room install.",
    priceMin: 800,
    priceMax: 5000,
    priceUnit: "quote review",
    defaultCrew: 2,
    defaultHours: 8,
    jobSize: "large",
    tags: ["flooring", "install", "removal"],
    customerNeeds: ["square feet", "photos", "floor type", "material status", "removal yes/no"],
    operationsSignal: "Needs sqft, prep, material, disposal, trim, and schedule review.",
  },
  {
    id: "roof_repair",
    categoryId: "projects",
    serviceCode: "roofing",
    shapeId: "repeat_loop",
    label: "Roof repair",
    description: "Leak, flashing, missing shingles, small patch, or storm repair.",
    priceMin: 250,
    priceMax: 1200,
    priceUnit: "repair quote",
    defaultCrew: 2,
    defaultHours: 3,
    jobSize: "quote_review",
    tags: ["roofing", "repair", "leak"],
    customerNeeds: ["roof photos", "leak location", "stories", "access", "urgency"],
    operationsSignal: "Needs safety review, ladder height, roof pitch, materials, and weather window.",
  },
  {
    id: "roofing_project",
    categoryId: "projects",
    serviceCode: "roofing",
    shapeId: "repeat_loop",
    label: "Roofing project",
    description: "Shingle work, tear-off, replacement, or larger roof scope.",
    priceMin: 2500,
    priceMax: 8000,
    priceUnit: "quote review",
    defaultCrew: 3,
    defaultHours: 8,
    jobSize: "large",
    tags: ["roofing", "tear-off", "replacement"],
    customerNeeds: ["roof photos", "roof size", "stories", "material type", "timeline"],
    operationsSignal: "Requires full quote review for safety, materials, dump, crew, and schedule.",
  },
  {
    id: "painting_room",
    categoryId: "projects",
    serviceCode: "painting",
    shapeId: "repeat_loop",
    label: "Painting room / small area",
    description: "Room painting, touch-up, trim, primer, or small exterior area.",
    priceMin: 300,
    priceMax: 900,
    priceUnit: "small paint job",
    defaultCrew: 2,
    defaultHours: 3,
    jobSize: "medium",
    tags: ["painting", "room", "trim"],
    customerNeeds: ["photos", "room count", "paint provided yes/no", "prep needed"],
    operationsSignal: "Capture sqft, prep, primer, material, ladder needs, and dry time.",
  },
  {
    id: "move_out_clean",
    categoryId: "projects",
    serviceCode: "move_cleaning",
    shapeId: "repeat_loop",
    label: "Move-out cleaning",
    description: "Turnover cleaning before or after moving, rental reset, or sale prep.",
    priceMin: 300,
    priceMax: 1200,
    priceUnit: "cleaning quote",
    defaultCrew: 2,
    defaultHours: 4,
    jobSize: "medium",
    tags: ["cleaning", "turnover", "move-out"],
    customerNeeds: ["home size", "photos", "rooms", "appliances", "preferred date"],
    operationsSignal: "Capture rooms, condition, appliances, supplies, and deadline.",
  },
];

export function formatServicePriceRange(task: ServicePriceMenuTask): string {
  return `$${task.priceMin.toLocaleString()}-$${task.priceMax.toLocaleString()}`;
}
